###
POST http://localhost:8080/admin/users
Content-Type: application/json

{
  "name": "Лиана",
  "email": "Liana@mail.ru"
}

###
POST http://localhost:8080/admin/categories
Content-Type: application/json

{
  "name": "Первая категория"
}

###
POST http://localhost:8080/users/1/events
Content-Type: application/json

{
  "annotation": "Сплав на байдарках похож на полет.",
  "category": 1,
  "description": "Сплав на байдарках похож на полет. На спокойной воде — это парение. На бурной, порожистой — выполнение фигур высшего пилотажа. И то, и другое дарят чувство обновления, феерические эмоции, яркие впечатления.",
  "eventDate": "2024-12-31 15:10:05",
  "location": {
    "lat": 55.754167,
    "lon": 37.62
  },
  "paid": true,
  "participantLimit": 10,
  "requestModeration": false,
  "title": "Сплав на байдарках"
}

###
GET http://localhost:8080/admin/events/waiting-review

###
PATCH http://localhost:8080/admin/events/reviews
Content-Type: application/json

{
  "1": {
    "annotation": null,
    "category": null,
    "description": null,
    "eventDate": null,
    "location": null,
    "paid": null,
    "participantLimit": null,
    "requestModeration": null,
    "stateAction": "REJECT_EVENT",
    "title": null,
    "commentsDtoList": [
      {
        "field": "CATEGORY",
        "comment": "Измените тип категории"
      }
    ]
  }
}

