version: '3.1'

services:
  stats-server:
    container_name: stats-server
    build: statistics-module/stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistics-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statistics-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    container_name: emw-service
    build: main-ewm-service-module
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    depends_on:
      - stats-db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-root@root.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}